"""A minimal OpenID Connect relying party.

Exists to prove the IdP is interoperable with code that knows nothing about its internals. It shares
no modules with ``app/`` on purpose: an RP built from the server's own helpers would prove only that
the server agrees with itself.

Every step is printed to the page so the flow can be inspected rather than taken on trust.
"""

from __future__ import annotations

import os
import secrets
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import urlencode

import httpx
import jwt
import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse, RedirectResponse

IDP_ISSUER = os.environ.get("AUTHFORGE_DEMO_ISSUER", "http://localhost:8000")
CLIENT_ID = os.environ.get("AUTHFORGE_DEMO_CLIENT_ID", "demo-web-client")
CLIENT_SECRET = os.environ.get("AUTHFORGE_DEMO_CLIENT_SECRET", "")
BASE_URL = os.environ.get("AUTHFORGE_DEMO_RP_URL", "http://localhost:8100")
RESOURCE_SERVER_URL = os.environ.get("AUTHFORGE_DEMO_API_URL", "http://localhost:8200")
REDIRECT_URI = f"{BASE_URL}/callback"
SCOPES = "openid profile email offline_access"

app = FastAPI(title="AuthForge Demo Relying Party", docs_url=None, redoc_url=None)


@dataclass
class PendingRequest:
    """What the RP must remember between the redirect out and the callback back.

    In a real RP this lives in the user's session, not in a process dictionary. The important
    part is that ``state``, ``nonce`` and ``code_verifier`` are generated by the *client* and
    never leave it (except the challenge), which is what makes the callback verifiable.
    """

    state: str
    nonce: str
    code_verifier: str


_pending: dict[str, PendingRequest] = {}


@dataclass
class Tokens:
    access_token: str = ""
    refresh_token: str = ""
    id_token: str = ""
    id_claims: dict[str, Any] = field(default_factory=dict)
    scope: str = ""


_tokens = Tokens()


async def discover() -> dict[str, Any]:
    """Read the discovery document instead of hard-coding endpoints.

    This is what makes signing-key rotation and endpoint changes invisible to the client.
    """
    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.get(f"{IDP_ISSUER}/.well-known/openid-configuration")
        response.raise_for_status()
        return dict(response.json())


@app.get("/", response_class=HTMLResponse)
async def home() -> str:
    signed_in = bool(_tokens.id_claims)
    body = [
        "<h1>AuthForge demo relying party</h1>",
        f"<p>Issuer: <code>{IDP_ISSUER}</code><br/>Client: <code>{CLIENT_ID}</code></p>",
    ]
    if not CLIENT_SECRET:
        body.append(
            "<p style='color:#b00'>Set <code>AUTHFORGE_DEMO_CLIENT_SECRET</code> first "
            "(printed by <code>make seed</code>).</p>"
        )
    if signed_in:
        body.append("<h2>ID token claims</h2><pre>" + _pretty(_tokens.id_claims) + "</pre>")
        body.append(f"<p>Granted scope: <code>{_tokens.scope}</code></p>")
        body.append(
            "<p><a href='/userinfo'>Call /userinfo</a> · "
            "<a href='/api'>Call the resource server</a> · "
            "<a href='/refresh'>Refresh the tokens</a> · "
            "<a href='/logout'>Forget them</a></p>"
        )
    else:
        body.append("<p><a href='/login'>Sign in with AuthForge</a></p>")
    return _page("".join(body))


@app.get("/login")
async def start_login() -> RedirectResponse:
    """Begin Authorization Code + PKCE."""
    metadata = await discover()
    # 32 bytes of CSPRNG each. `state` defends the callback against CSRF; `nonce` binds the ID token
    # to this attempt; the verifier binds the code to this client instance.
    pending = PendingRequest(
        state=secrets.token_urlsafe(32),
        nonce=secrets.token_urlsafe(16),
        code_verifier=secrets.token_urlsafe(64)[:128],
    )
    _pending[pending.state] = pending

    parameters = {
        "response_type": "code",
        "client_id": CLIENT_ID,
        "redirect_uri": REDIRECT_URI,
        "scope": SCOPES,
        "state": pending.state,
        "nonce": pending.nonce,
        # Only the challenge is sent; the verifier stays here until the exchange.
        "code_challenge": _s256(pending.code_verifier),
        "code_challenge_method": "S256",
    }
    return RedirectResponse(f"{metadata['authorization_endpoint']}?{urlencode(parameters)}")


@app.get("/callback", response_class=HTMLResponse)
async def callback(request: Request) -> str:
    error = request.query_params.get("error")
    if error:
        return _page(
            f"<h1>Authorization failed</h1><p><code>{error}</code>: "
            f"{request.query_params.get('error_description', '')}</p><p><a href='/'>Back</a></p>"
        )

    state = request.query_params.get("state", "")
    # A callback whose `state` this RP never issued is either a CSRF attempt or a replay, and
    # must be discarded before the code is exchanged for anything.
    pending = _pending.pop(state, None)
    if pending is None:
        raise HTTPException(status_code=400, detail="unknown or replayed state")

    code = request.query_params.get("code", "")
    metadata = await discover()
    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.post(
            metadata["token_endpoint"],
            data={
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": REDIRECT_URI,
                "code_verifier": pending.code_verifier,
            },
            auth=(CLIENT_ID, CLIENT_SECRET),
        )
    if response.status_code != 200:
        return _page(f"<h1>Token exchange failed</h1><pre>{response.text}</pre>")

    payload = response.json()
    claims = await _validate_id_token(payload["id_token"], metadata, nonce=pending.nonce)
    _tokens.access_token = payload["access_token"]
    _tokens.refresh_token = payload.get("refresh_token", "")
    _tokens.id_token = payload["id_token"]
    _tokens.id_claims = claims
    _tokens.scope = payload.get("scope", "")
    return _page(
        "<h1>Signed in</h1><p>ID token signature, issuer, audience, expiry and nonce all "
        f"verified.</p><pre>{_pretty(claims)}</pre><p><a href='/'>Continue</a></p>"
    )


@app.get("/refresh", response_class=HTMLResponse)
async def refresh() -> str:
    """Use the refresh token, then show that the presented one is now dead.

    Demonstrating rotation from the client's side matters: an RP that keeps the old token around and
    retries with it will trip the IdP's reuse detection and lose the whole session.
    """
    if not _tokens.refresh_token:
        return _page("<h1>No refresh token</h1><p><a href='/'>Back</a></p>")
    metadata = await discover()
    previous = _tokens.refresh_token
    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.post(
            metadata["token_endpoint"],
            data={"grant_type": "refresh_token", "refresh_token": previous},
            auth=(CLIENT_ID, CLIENT_SECRET),
        )
        if response.status_code != 200:
            return _page(f"<h1>Refresh failed</h1><pre>{response.text}</pre>")
        payload = response.json()
        _tokens.access_token = payload["access_token"]
        _tokens.refresh_token = payload.get("refresh_token", "")
        if payload.get("id_token"):
            _tokens.id_token = payload["id_token"]
            _tokens.id_claims = await _validate_id_token(payload["id_token"], metadata, nonce=None)

        replay = await client.post(
            metadata["token_endpoint"],
            data={"grant_type": "refresh_token", "refresh_token": previous},
            auth=(CLIENT_ID, CLIENT_SECRET),
        )
    return _page(
        "<h1>Refreshed</h1>"
        "<p>A new refresh token was issued in the same family and the presented one was spent.</p>"
        f"<p>Replaying the old token returned <code>{replay.status_code}</code>: "
        f"<code>{replay.json().get('error')}</code> — and that reuse signal revoked the whole "
        "family, so this session now needs a fresh sign-in.</p>"
        "<p><a href='/login'>Sign in again</a></p>"
    )


@app.get("/userinfo", response_class=HTMLResponse)
async def userinfo() -> str:
    metadata = await discover()
    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.get(
            metadata["userinfo_endpoint"],
            headers={"Authorization": f"Bearer {_tokens.access_token}"},
        )
    return _page(
        f"<h1>/userinfo → {response.status_code}</h1><pre>{_pretty(response.json())}</pre>"
        "<p><a href='/'>Back</a></p>"
    )


@app.get("/api", response_class=HTMLResponse)
async def call_resource_server() -> str:
    async with httpx.AsyncClient(timeout=10) as client:
        response = await client.get(
            f"{RESOURCE_SERVER_URL}/reports",
            headers={"Authorization": f"Bearer {_tokens.access_token}"},
        )
    return _page(
        f"<h1>Resource server → {response.status_code}</h1><pre>{_pretty(response.json())}</pre>"
        "<p><a href='/'>Back</a></p>"
    )


@app.get("/logout")
async def logout() -> RedirectResponse:
    _tokens.access_token = _tokens.refresh_token = _tokens.id_token = ""
    _tokens.id_claims = {}
    return RedirectResponse("/")


async def _validate_id_token(
    id_token: str, metadata: dict[str, Any], *, nonce: str | None
) -> dict[str, Any]:
    """Validate an ID token the way OIDC Core §3.1.3.7 requires.

    All five checks matter. Signature alone proves the token came from the IdP but not that it was
    meant for this client (`aud`), that it is still current (`exp`), that it came from the expected
    issuer (`iss`), or that it belongs to *this* login attempt (`nonce`).
    """
    async with httpx.AsyncClient(timeout=10) as client:
        jwks_response = await client.get(metadata["jwks_uri"])
        jwks_response.raise_for_status()
    key_set = jwt.PyJWKSet.from_dict(jwks_response.json())
    kid = jwt.get_unverified_header(id_token).get("kid")
    signing_key = next((key for key in key_set.keys if key.key_id == kid), None)
    if signing_key is None:
        raise HTTPException(status_code=400, detail="ID token signed by an unpublished key")

    claims = jwt.decode(
        id_token,
        signing_key.key,
        algorithms=metadata["id_token_signing_alg_values_supported"],
        audience=CLIENT_ID,
        issuer=metadata["issuer"],
    )
    if nonce is not None and claims.get("nonce") != nonce:
        raise HTTPException(status_code=400, detail="ID token nonce does not match this request")
    return dict(claims)


def _s256(verifier: str) -> str:
    import base64
    import hashlib

    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def _pretty(payload: Any) -> str:
    import html
    import json

    return html.escape(json.dumps(payload, indent=2, sort_keys=True))


def _page(body: str) -> str:
    return (
        "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Demo RP</title>"
        "<style>body{font-family:system-ui,sans-serif;max-width:46rem;margin:3rem auto;"
        "padding:0 1rem;line-height:1.55}pre{background:#f4f6fa;padding:1rem;border-radius:8px;"
        "overflow-x:auto}code{background:#f4f6fa;padding:.1rem .3rem;border-radius:4px}"
        "a{color:#3b6fd4}</style></head><body>" + body + "</body></html>"
    )


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8100)
